spring.application.name=portfolio-backend

# Dynamic port for Render
server.port=${PORT:8080}

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Use environment variables (IMPORTANT)
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Debug (optional)
logging.level.org.springframework.mail=DEBUG
